### ISSUE TITLE
[Bug] - Person entities with no DOB throw unhelpful error

### ISSUE THREAD

**Issue by JonShort** [weiran/dead-or-alive-bot#7]
### Description
When an entity is returned from wikidata which doesn't have a date of birth, an unhelpful error is returned to the user.

![image](https://user-images.githubusercontent.com/21317379/40784601-fbfbfa40-64dd-11e8-9d70-6d624d328c11.png)

### To Reproduce
- Using the bot, search for `mini menon`.
- The error `Cannot read property '0' of undefined` will be returned.

### Cause
When resolving the date of birth, the code looks for key `0` in an array which doesn't exist when there's no date of birth.

![image](https://user-images.githubusercontent.com/21317379/40780290-bf91b6a2-64cf-11e8-9f29-98887f5474a8.png)

### Potential solutions
- Handle the array being undefined (wrap in a `try`/`catch` or use `idx`) and:
  - provide a nicer error to the user
or
  - continue to provide the details of the entity, but explain the DOB doesn't exist

**Comment by weiran** [comment]
Resolved by #8.
